### PR TITLE
no derps this time :p

### PR DESCRIPTION
**Pull request by sarthakspiker**

### CODE REVIEW

**Comment by StarkDroid** [comment]
aah oh my goodness sarthak!!! hwkeys: add a swap keys switch you have inserted the whole gzr_strings!!! 
https://github.com/TipsyOs/packages_apps_Settings/commit/438f5f2bb73a0cea2cfd12d2b1402fb3054fdfa3
look at that commit carefully its just the two lines not the whole string! do you know how many duplicates you'll face on building? -_- those string have reference to no value either or are already assigned in other strings!
still call it "no derps this time :P"

**Comment by srisurya95** [comment]
For stark's and cyanogen's sake please compile before pushing and test out the code

**Comment by owlseye** [comment]
com.android.settings.tipsy.ButtonBacklightBrightness
doesn't exists as well....
You did the same with hardwarekey_settings.xml what Stark said about the strings.

**Comment by Martinusbe** [comment]
practice makes perfect

**Comment by owlseye** [comment]
@Martinusbe But not on our github😬
Please do not open pull requests until you compiled and tested.

**Pull request closed without merging**
